### ISSUE TITLE
Styling tweaks

### ISSUE THREAD

**Issue by jussiarpalahti** [City-of-Helsinki/devheldev#28]
One combined issue for styling tweaks, @terotic

- [x] Button hover makes text disappear (white on light yellow)
- [x] Project list as boxes. Each has image. Style project status (color/icon?)
- [ ] Project page: tech lead (people list). Performance indicators? Navigation on sidebar? 
- [ ] API page: style
- [ ] About us: People list (sidebar?) (people are about us child pages in cms)
- [ ] Events: own page? waiting for content (FB - API)
- [ ] Sub pages needs to have larger title/H1 style, now uses same style that FP info boxes
- [ ] Mobile top bar with logo and burger don't work (background missing), solution needed (align large 
- [x] Check top bar on desktop Firefox
- [x] H1 > H2 difference is not that large
- [x] Form layout (bootstrap, pure css, material?) (api/add/)
- [x] Front page hero size smaller + responsive
logo on layout left)

**Comment by terotic** [comment]
Form: /api/add/
